"""Password hashing and short-lived bearer-token helpers."""

import base64
import hashlib
import hmac
import secrets
from datetime import datetime, timedelta, timezone

import jwt
from fastapi import HTTPException, status
from jwt import InvalidTokenError

from app.config import get_settings


PASSWORD_ALGORITHM = "scrypt"
TOKEN_ALGORITHM = "HS256"
_revoked_token_ids: set[str] = set()


def hash_password(password: str) -> str:
    """Hash a password using salted scrypt from the Python standard library."""

    salt = secrets.token_bytes(16)
    digest = hashlib.scrypt(password.encode("utf-8"), salt=salt, n=2**14, r=8, p=1)
    return "$".join(
        [
            PASSWORD_ALGORITHM,
            "16384",
            "8",
            "1",
            base64.b64encode(salt).decode("ascii"),
            base64.b64encode(digest).decode("ascii"),
        ]
    )


def verify_password(password: str, stored_hash: str) -> bool:
    """Verify a password against a hash generated by ``hash_password``."""

    try:
        algorithm, n, r, p, salt, expected = stored_hash.split("$")
        if algorithm != PASSWORD_ALGORITHM:
            return False
        calculated = hashlib.scrypt(
            password.encode("utf-8"),
            salt=base64.b64decode(salt),
            n=int(n),
            r=int(r),
            p=int(p),
        )
        return hmac.compare_digest(calculated, base64.b64decode(expected))
    except (ValueError, TypeError):
        return False


def create_access_token(user_id: int) -> str:
    """Create a signed token with a unique identifier for logout revocation."""

    settings = get_settings()
    now = datetime.now(timezone.utc)
    payload = {
        "sub": str(user_id),
        "jti": secrets.token_urlsafe(16),
        "iat": now,
        "exp": now + timedelta(minutes=settings.access_token_expire_minutes),
    }
    return jwt.encode(payload, settings.auth_secret_key, algorithm=TOKEN_ALGORITHM)


def decode_access_token(token: str) -> dict[str, object]:
    """Validate a token and return its claims, raising a consistent 401 on failure."""

    try:
        payload = jwt.decode(token, get_settings().auth_secret_key, algorithms=[TOKEN_ALGORITHM])
        if not payload.get("sub") or not payload.get("jti") or payload["jti"] in _revoked_token_ids:
            raise InvalidTokenError("Invalid or revoked token")
        return payload
    except InvalidTokenError as exc:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid, expired, or revoked access token",
            headers={"WWW-Authenticate": "Bearer"},
        ) from exc


def revoke_access_token(token: str) -> None:
    """Invalidate the current token for this development process."""

    payload = decode_access_token(token)
    _revoked_token_ids.add(str(payload["jti"]))
